### ISSUE TITLE
framework-arduinointel is out of date

### ISSUE THREAD

**Issue by anweiss** [platformio/platform-intel_arc32#3]
Any chance the `framework-arduinointel` package can be updated to reflect the latest stable release of Core and supporting libraries? Relates to #2

**Comment by valeros** [comment]
Hi @anweiss !
`framework-arduinointel` package has been updated, could you please retest it from dev branch?
```
pio platform uninstall intel_arc32
pio platform install https://github.com/platformio/platform-intel_arc32.git
```
