### ISSUE TITLE
toolchain-xtensa32

### ISSUE THREAD

**Issue by pmaduarte** [platformio/platform-intel_arc32#6]
Hi,

I'm having this error on "run".

[Fri Aug 11 17:48:13 2017] Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PackageManager: Installing toolchain-xtensa32 @ ~1.50200.0
Error: Could not find a version that satisfies the requirement '~1.50200.0' for your system 'linux_armv7l'

How do i solve this?

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif32/issues
